<?php

/**
 * @file
 * Fixes incompatible Media Gallery dependency with Multiform module.
 */

/**
 * Multiform hardcoded dependecy to modify.
 */
define('MEDIA_GALLERY_MULTIFORM_DEPENDENCY', 'multiform (1.0-beta2)');

/**
 * Implements hook_system_info_alter().
 */
function media_gallery_installer_system_info_alter(&$info, $file, $type) {
  if ($type == 'module' && $file->name == 'media_gallery') {
    $key = array_search(MEDIA_GALLERY_MULTIFORM_DEPENDENCY, $info['dependencies']);
    if ($key !== FALSE) {
      $info['dependencies'][$key] = 'multiform';
    }
  }
}
